### ISSUE TITLE
Is there still going to be updates for hacktv?

### ISSUE THREAD

**Issue by 03stevensmi** [fsphil/satradio#1]
hey mate,
Are you still working on hacktv?

Its gone a bit quiet and I'm worried that you may have moved onto something else.

Is there still going to be updates and progress with hacktv?

Cheers.
Michael. S

**Comment by fsphil** [comment]
I've had little time for hobby projects lately, but there's always something going on. This project will eventually connect to hacktv. If there's something you think should get some attention, open an issue over on the hacktv page.
